config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:show]
  resources :pets, only: [:index, :show, :new, :create, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pet
  has_many :reviews
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  validates :name, :age, :category, :diet, presence: true
  has_many :bookings
  has_many :reviews, through: :booking
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, presence: true, length: {minimum: 5}
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pets
  has_many :bookings, through: :pets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :address])
  end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def index
    Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @booking = Booking.new(booking_params)
    @booking.pet = @booking
    if @booking.save!
      redirect_to user_path(current_user)
    else
      render :new
    end
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @pet = Pet.find(params[:pet_id])
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @booking = Booking.new(booking_params)
    @booking.pet = @pet
    @booking.user = current_user
    if @booking.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
   skip_before_action :authenticate_user!
  def show
    @pet = Pet.find(params[:id])
    @booking = Booking.new
    # @user = Pet.user_id
  end

  def index
    @pets = Pet.all
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end


  private

  def pet_params
    params.require(:pet).permit(:name, :diet, :category, :age, :medical_situation, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
   def create
    @review = Review.new(review_params)
    @booking = booking.find(params[:booking_id])
    @review.booking = @booking
    if @review.save
      redirect_to booking_path(@booking)
    else
      render 'bookings/show'
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to booking_path(@review.booking)
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @bookings = Booking.where(user_id: @user.id)
    @pets = Pet.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container">
  <h1> Book this pet!</h1>
  <div class = "container text-left">
    <%= simple_form_for [@pet, @booking] do |f| %>
      <%= f.input :start_date, html5: true %>
      <%= f.input :end_date, html5: true %>
      <div class="d-flex justify-content-center">
        <%= f.submit 'Book', class: "btn-flat", id: "btn-book" %>
      </div>
    <% end %>
  </div>

</div>

app/views/bookings/new.html.erb
<%= render 'form', booking: @booking %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petyy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
<div class="page-container">
<%= render "shared/navbar" %>
 <%= yield %>
 <div class="footer-container"><%= render "shared/footer" %></div>
</div>
  </body>
</html>

app/views/pages/home.html.erb
<%# <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> %>
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-black">
    <h1>Petyy</h1>
    <p>Happy pets. Happy owners.</p>
    <h3 class="typed-js" data-controller="typed-js"></h3>
  </div>
</div>
<div class="d-flex container py-5 justify-content-center" >
<%= link_to "Look at our cuties!", pets_path, class: "btn btn-flat", id: "btn-home"%>
</div>

app/views/pets/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <%= simple_form_for @pet do |f| %>
          <%= f.input :name, placeholder: 'Pet name' %>
          <%= f.input :age, placeholder: 'Pet age' %>
          <%= f.input :category, placeholder: 'Category', collection: %w[Cat Dog Snakes Crocodile Tiger Mongoose Cow Monkey
Coati Gemsbok Dugong Hartebeest Steer Chipmunk Basilisk Ewe Kangaroo Bunny Fish Mustang Gopher Ocelot Chimpanzee Badger] %>
          <%= f.input :medical_situation, placeholder: 'Medical condition' %>
          <%= f.input :diet, placeholder: 'Diet' %>
          <%= f.input :photo, as: :file%>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pets/_pet_card.html.erb
<div class="card-trip">
  <p><%#= cl_image_tag pet.photo.key, height: 200, width: 300, crop: :fill%>
    <% if @pet.photo.nil? %>
      <%=cl_image_tag("non_existing_id.png", :default_image => "my_default_image_mciyv8.jpg", height: 300, width: 400, crop: :fill) %>
    <% else %>
      <%= cl_image_tag @pet.photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  </p>
  <div class="card-trip-infos">
    <h2><%= pet.name %></h2>
    <p><%= pet.category %>, <%= pet.age %> years old</p>
    <% if something %>
      <p>BANANA</p>
    <% end %>
  </div>
</div>

app/views/pets/edit.html.erb
<div class="container ">
  <div class="d-flex justify-content-center align-text-center mt-5">
    <h2>Edit your pet</h2>
  </div>
<%= render 'form', pet: @pet %>
</div>

app/views/pets/index.html.erb
<%
=begin %>
<ul>
<% @pets.each do |pet| %>
<li>Name: <%=link_to "#{pet.name}", pet_path(pet) %> - Species: <%=pet.category%></li>
<% end %>
</ul>
<%
=end %>

<h1 style="text-align: center" class="p-2">Our Cuties!</h1>


    <div class="flex-container">
      <% if (@pets.count == 0) %>
      <p>No pet registered yet</p>
      <% else %>
        <% @pets.each do | pet | %>


          <%= link_to pet_path(pet), class: 'decoration-none' do%>
            <%= render 'pet_card', pet: pet, something: false %>
          <% end %>


        <% end %>
      <% end %>
    </div>

app/views/pets/new.html.erb
<div class="container ">
  <div class="d-flex justify-content-center align-text-center mt-5">
    <h2>Create a new pet</h2>
  </div>
<%= render 'form', pet: @pet %>
</div>

app/views/pets/show.html.erb
<div class= "d-flex flex-column align-items-center">
  <div class="container card-white p-3 row justify-content-start">
    <div class = "container d-flex flex-column justify-content-center mb-3">
      <h2>Hello, I'm <strong><%= @pet.name %></strong>🍀</h2>
    </div>
      <div class="container justify-content-between" >
        <div class =" justify-content-between"  >
          <div class=" jusify-content-between align-items-top">
            <div>
              <p>
              <% if @pet.photo.nil? %>
                <%=cl_image_tag("non_existing_id.png", :default_image => "my_default_image_mciyv8.jpg", height: 300, width: 400, crop: :fill) %>
              <% else %>
                <%= cl_image_tag @pet.photo.key, height: 300, width: 400, crop: :fill %>
              <% end %>
               </p>
                <div class="container align-items-left" id="pet-info-box">
                  <h5>I'm a lovely <strong><%= @pet.category %></strong>, and eat <strong><%= @pet.diet %></strong></h5>
                  <br>
                  <h5>My owner is <strong><%= @pet.user.first_name%></strong>! I live in <strong><%= @pet.user.address%></strong>🏠</h5>
                  <br>
                  <h5>Species: <%= @pet.category %></h5>
                  <br>
                  <h5>Age: <%= @pet.age %></h5>
                  <br>
                    <div class= "d-flex flex-row">
                      <h5>Medical Situation:<% if @pet.medical_situation.empty? %>
                      <%= "I am perfectly healthy!" %>
                      <% else%>
                        <%= "#{@pet.medical_situation}"%>
                      <% end %></h5>
                    </div>
                </div>

            </div>
          </div>
      </div>
    </div>
  </div>


    <div class="container card-white p-3 row justify-content-center height-fit-content">
      <div class = "form">
        <%= render 'bookings/form'%>
      </div>
      </div>
        </div>
        </div>
        <div class= " d-flex justify-content-center align-items-center ">
        <div class= "btn-ghost mb-4" id = "btn-cancel"><%= link_to "Back to the list", pets_path%></div>

      </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <p>&copy; 2021 Petyy <i class="fas fa-paw"></i></p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon p-4">
  <a class="navbar-brand" href="/">
    <img src="https://www.pinclipart.com/picdir/big/576-5767387_dog-icon-transparent-background-clipart.png"/>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav align-items-center justify-content-between mr-auto">
      <li><%= link_to "home", root_path, class: "navilist" %></li>
      <li><% if current_user.present? %>
          <%= link_to "dashboard", user_path(current_user), class: "navilist"  %>
          <% end %></li>
      <li><%= link_to "pets", pets_path, class: "navilist"  %></li>

      <li class="nav-item dropdown">
      <% if current_user.present? %>
        <% if current_user.email == "akiho@lewagon.com" %>
        <% avatar = "https://i.picsum.photos/id/1011/5472/3648.jpg?hmac=Koo9845x2akkVzVFX3xxAc9BCkeGYA9VRVfLE4f0Zzk" %>
        <% else %>
        <% avatar = "https://www.matthes-seitz-berlin.de/fs/authors/maruan-paschen/005355.big.jpg"%>
        <% end %>
        <% else %>
        <% avatar = "https://www.matthes-seitz-berlin.de/fs/authors/maruan-paschen/005355.big.jpg"%>
        <% end %>
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= avatar %>" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if current_user.present? %>
          <%= link_to "My Page", user_path(current_user), class: "dropdown-item" %>
          <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "dropdown-item" %>
          <% end %>
          <% if current_user.present? %>
          <%= link_to "logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
           <% end %>

        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/users/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1557246565-8a3d3ab5d7f6?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8Y2F0c3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1400&q=60);">
  <div class="container">
   <h1>Hello <%= @user.first_name %>👋🏻</h1>
  </div>
</div>

<div class="container">
  <div class="card-white p-3">
    <h3 style="font-weight:bold">Your pets</h3>

    <div class="flex-container">
      <% if (@pets.count == 0) %>
        <p>No pet registered yet</p>
      <% else %>
          <% @pets.each do | pet | %>
            <%= link_to pet_path(pet), class: 'decoration-none' do%>
            <%= render 'pets/pet_card', pet: pet, something: false %>
            <% end %>
          <% end %>
       <% end %>
    </div>

    <div>
      <%= link_to "Register new pet", new_pet_path, class: "btn btn-flat" %>
    </div>
  </div>

  <div class="card-white p-3">
    <h3 style="font-weight:bold">Your bookings</h3>
    <div class="flex-container">
      <% if (@bookings.count == 0) %>
      <p>No bookings made yet</p>
      <% else %>
        <% @bookings.each do | booking | %>
          <div class="card-trip">
            <%= cl_image_tag booking.pet.photo.key, crop: :fill %>
            <div class="card-product-infos">
              <h2><%= Pet.find(booking.pet_id).name %></h2>
              <p>Start date: <%= booking.start_date.strftime("%b %e, %y") %></p>
              <p>End date: <%= booking.end_date.strftime("%b %e, %y") %></p>
            </div>
        </div>
        <% end %>
      <% end %>
    </div>
    <div>
      <%= link_to 'Back to pets page', pets_path, class: "btn btn-green"%>
    </div>
  </div>
</div>